# UTAG=value DPORT=value docker-compose build
# docker-compose up

version: "3.7"

services:
  drill:
    build: ./
    image: wumingzhilian/setuid-backdoor-level40:v1
    container_name: setuid-backdoor-level40
    ports:
      - 56105:2908
    privileged: false
