# UTAG=value DPORT=value docker-compose build
# docker-compose up

version: "3.7"

services:
  drill:
    build: ./
    image: wumingzhilian/buffer-overflow-level14:v1
    container_name: buffer-overflow-level14
    ports:
      - 56105:2674
    privileged: false
