# UTAG=value DPORT=value docker-compose build
# docker-compose up

version: "3.7"

services:
  drill:
    build: ./
    image: wumingzhilian/elf-crackme-level10:v1
    container_name: elf-crackme-level10
    ports:
      - 56105:2810
    privileged: false
