# UTAG=value DPORT=value docker-compose build
# docker-compose up

version: "3.7"

services:
  drill:
    build: ./
    image: wumingzhilian/shellcode-injection-level11:v1
    container_name: shellcode-injection-level11
    ports:
      - 56105:2870
    privileged: false
