# UTAG=value DPORT=value docker-compose build
# docker-compose up

version: "3.7"

services:
  drill:
    build: ./
    image: wumingzhilian/return-oriented-programming-level10:v1
    container_name: return-oriented-programming-level10
    ports:
      - 56105:2425
    privileged: false
