# UTAG=value DPORT=value docker-compose build
# docker-compose up

version: "3.7"

services:
  drill:
    build: ./
    image: wumingzhilian/setuid-backdoor-level41:v1
    container_name: setuid-backdoor-level41
    ports:
      - 56105:2076
    privileged: false
