# UTAG=value DPORT=value docker-compose build
# docker-compose up

version: "3.7"

services:
  drill:
    build: ./
    image: wumingzhilian/use-after-free-level10:v1
    container_name: use-after-free-level10
    ports:
      - 56105:2907
    privileged: false
