# UTAG=value DPORT=value docker-compose build
# docker-compose up

version: "3.7"

services:
  drill:
    build: ./
    image: wumingzhilian/setuid-backdoor-level20:v1
    container_name: setuid-backdoor-level20
    ports:
      - 56105:2660
    privileged: false
